export const BRANDS = [
  'Auer - Collins',
  'Conroy - Nolan',
  'Smith, Jerde-Rolfson and Konopelski',
  'Schmitt - Legros',
  'Bradtke, Feil and Heathcote',
  'Rolfson, Cummings and Paucek',
  'Daugherty - Welch-Brekke',
  'Wolf - Wolff',
  'Hilll - Beahan',
  'Bernhard Group',
  'Heller, Legros and Murray',
  'Terry - Kirlin',
  'Glover Inc',
  'Hoeger LLC',
  'McCullough, Botsford and Boyer',
  "Murray - Nikolaus-O'Kon",
  'Kub Inc',
  'Upton, Kirlin and Crist',
  'Jakubowski, Moen and Wintheiser',
  'Feeney - Leuschke',
  'Roob - Cruickshank',
  'Fahey - Renner',
  'Raynor - Reinger',
  'Heller - Braun',
  'Tremblay LLC',
  'Schinner and Sons',
  'Gerhold, Rutherford and Mayer',
  'Runte, Stiedemann and Crooks',
  "Marvin - O'Reilly",
];
